### ISSUE TITLE
Kvdb high mem usage

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-introspector#105]
We have to investigate if this is a bug, or an inefficiency of the way to measure kv sizes

![9AC5264E-2EBE-4C42-8692-08E29C1FF3DC](https://user-images.githubusercontent.com/54316454/189158231-bff2e1c4-b95a-467a-90d7-339278b910c8.png)

Seems to be related to db size

4.0K    ./data/chains/versi_v1_9/db/full/pvf-artifacts
20M     ./data/chains/versi_v1_9/db/full/parachains/db
20M     ./data/chains/versi_v1_9/db/full/parachains
44G     ./data/chains/versi_v1_9/db/full
44G     ./data/chains/versi_v1_9/db
4.0K    ./data/chains/versi_v1_9/network
32K     ./data/chains/versi_v1_9/keystore
44G     ./data/chains/versi_v1_9
44G     ./data/chains

**Comment by PierreBesson** [comment]
So this issue is affecting our deployment of 2 kvdb-introspector sidecar (running `paritytech/polkadot-introspector:9d5f23fb`)
1. relay-kvdb: `polkadot-introspector kvdb --db /data/chains/versi_v1_9/db/full --db-type rocksdb prometheus --port 9620`
2. para-kvdb: `polkadot-introspector kvdb --db /data/chains/versi_v1_9/db/full/parachains/db --db-type rocksdb prometheus --port 9621`
The database disk size are:
1. 44 Gb for relay-chain db (`./data/chains/versi_v1_9/db`)
2. 20 Mb for the para-chain db (`./data/chains/versi_v1_9/db/full/parachains/db`)

![image](https://user-images.githubusercontent.com/513471/189159672-861aa080-f9d4-4517-83d2-e018d0206d7d.png)

**Comment by sandreim** [comment]
Fix confirmed on last deployment.
