### ISSUE TITLE
Support for on-demand parachains

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-introspector#375]
The on-demand parachain feature is currently under development. As soon as we have it merged in the Rococo runtime, we should look into implementing:
- claim queue monitoring - https://github.com/paritytech/polkadot/blob/alex/parathreads_review/runtime/parachains/src/scheduler.rs#L122
- bidding extrinsics
- latency between bid, claim and actual block production

**Comment by vstakhov** [comment]
The tracker code should be able to support basic on-demand parachains tracking (with inactivity timeout). The rest is indeed would be useful to add.

**Comment by AndreiEres** [comment]
With @antonva we decided that it would be useful to track `OnDemandOrderPlaced`

**Comment by AndreiEres** [comment]
- [x] **claim queue monitoring**
Monitoring the claim queue instead of deprecated `scheduled` state call to check cores occupancy.

- [ ] **bidding extrinsics**
Tracking of event `OnDemandOrderPlaced { para_id: ParaId, spot_price: BalanceOf<T> }`.

- [ ] **latency between bid, claim and actual block production**
Tracking of a length in blocks between relay block with event `OnDemandOrderPlaced` and relay block where parablock from the corresponding parachain was included.
